name: Release projects

on:
  push:
    branches:
    - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Bungee and Paper JARs
      run: ./gradlew :bungeecord:shadowJar :paper:shadowJar

    - name: Upload Bungee JAR as artifact
      uses: actions/upload-artifact@v3
      with:
        name: BedrockGUI-Bungee
        path: bungeecord/build/libs/BedrockGUI-Bungee-*.jar

    - name: Upload Paper JAR as artifact
      uses: actions/upload-artifact@v3
      with:
        name: BedrockGUI-Paper
        path: paper/build/libs/BedrockGUI-Paper-*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: BedrockGUI-Bungee
        path: .

    - name: Download Paper JAR
      uses: actions/download-artifact@v3
      with:
        name: BedrockGUI-Paper
        path: .

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: |
          ./BedrockGUI-Bungee-*.jar
          ./BedrockGUI-Paper-*.jar
